import { Poppins, Noto_Sans_JP, Crimson_Text} from "next/font/google";
import "./globals.css";

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["100", "200","300","400","500","600","700","800","900"], 
  variable:' --font-Poppins',
});

const noto = Noto_Sans_JP({ 
  subsets: ["latin"], 
  weight: ["100", "200","300","400","500","600","700","800","900"],
  variable:'--font-Noto_Sans_JP',
});

const crimson = Crimson_Text({ 
  subsets: ["latin"], 
  weight: ["400","600","700"],
  variable:'--font-Crimson_Text', 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${noto.variable} ${crimson.variable}`}>{children}</body>
    </html>
  );
}
